trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - template: templates/build.yml
        parameters:
          buildConfiguration: $(buildConfiguration)

#  - stage: Deploy
#    displayName: Deploy Stage
#    dependsOn: Build
#    condition: succeeded()
#    jobs:
#      - template: templates/deploy.yml
#        parameters:
#          environment: 'production'
#          buildConfiguration: $(buildConfiguration)
